- name: Disabilita swap
  shell: swapoff -a

- name: Installa pacchetti di base
  apt:
    name:
      - apt-transport-https
      - curl
      - gnupg
      - ca-certificates
      - software-properties-common
      - containerd
    update_cache: yes

- name: Abilita e avvia containerd
  systemd:
    name: containerd
    enabled: true
    state: started

- name: Configura sysctl per Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1

- name: Applica sysctl
  shell: sysctl --system

- name: Aggiungi key per repo Kubernetes
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Aggiungi repository Kubernetes
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present

- name: Installa kubelet, kubeadm, kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    update_cache: yes

- name: Disabilita aggiornamenti automatici kube*
  shell: apt-mark hold kubelet kubeadm kubectl
