- name: Crea VM libvirt via XML
  hosts: localhost
  gather_facts: no
  connection: local
  vars:
    vm_list:
      - k8s-master
      - k8s-worker1
      - k8s-worker2
  
  become: true   

  tasks:
    - name: Crea i dischi se non esistono
      command: qemu-img create -f qcow2 /var/lib/libvirt/images/{{ item }}.qcow2 10G
      args:
        creates: "/var/lib/libvirt/images/{{ item }}.qcow2"
      loop: "{{ vm_list }}"

    - name: Definisce la VM
      community.libvirt.virt:
        command: define
        xml: "{{ lookup('template', 'templates/vm_template.xml.j2') }}"
      vars:
        vm_name: "{{ item }}"
      loop: "{{ vm_list }}"

    - name: Avvia la VM
      community.libvirt.virt:
        name: "{{ item }}"
        state: running
      loop: "{{ vm_list }}"
